services:
  slurmctld:
    volumes:
      - /mnt/lustre:/lustre
  c1:
    volumes:
      - /mnt/lustre:/lustre
  c2:
    volumes:
      - /mnt/lustre:/lustre
  c3:
    volumes:
      - /mnt/lustre:/lustre
  c4:
    volumes:
      - /mnt/lustre:/lustre
  # Run inside Lima VM, use local Docker socket
  # Override in lima vm: docker-compose -f docker-compose.yml -f docker-compose.lustre.yml up
