services:
  slurmctld:
    volumes:
      - /mnt/lustre:/lustre
    environment:
      - LUSTRE_ENABLED=1
  c1:
    volumes:
      - /mnt/lustre:/lustre
    environment:
      - LUSTRE_ENABLED=1
  c2:
    volumes:
      - /mnt/lustre:/lustre
    environment:
      - LUSTRE_ENABLED=1
  c3:
    volumes:
      - /mnt/lustre:/lustre
    environment:
      - LUSTRE_ENABLED=1
  c4:
    volumes:
      - /mnt/lustre:/lustre
    environment:
      - LUSTRE_ENABLED=1
